# stage 1 build
FROM golang:1.14.0-alpine as builder
WORKDIR /mysource
COPY hello.go .
RUN GOOS=linux go build -a -installsuffix cgo -o hello . 

#stage 2 run
FROM alpine:latest
WORKDIR /app
COPY --from=builder /mysource/hello .
CMD ["./hello"]