apiVersion: v1
kind: Secret
metadata:
  name: my-secret
data:
  username: aGFtZWQ=
  password: bXlwYXNzd29yZDEyMw==
---
apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  restartPolicy: Never
  containers:
  - name: ubuntu
    image: ubuntu
    env:
    - name: "app_username"
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: username
    - name: "app_password"
      valueFrom:
        secretKeyRef:
          name: my-secret
          key: password
    args:
    - env    